---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pack

<!-- badges: start -->
<!-- badges: end -->

This package provides some shape-packing functions. It's a work in progress, full of bugs and inefficiencies.

## Installation

You can install the development version of pack like so:

``` r
pak::pak("robbrotherton/pack")
```

## Example


```{r example}
library(pack)
library(ggplot2)

set.seed(123)

container <- draw::polygon(sides = 6, radius = 100)

radii <- c(rep(30, 2),
           rep(20, 4),
           rep(10, 20),
           rep(5, 200), 
           rep(3, 300),
           rep(2, 500),
           rep(1, 500),
           rep(0.5, 1000))

circles <- pack_circles_all(container, 
                        radii = radii, 
                        existing_circles = data.frame(x = 0, y = 0, r = 0)) |> 
  dplyr::mutate(fill = factor(round(runif(dplyr::n(), min = 1, max = 4), 0)))

ggplot(circles) +
  geom_polygon(data = container, aes(x, y)) +
  ggforce::geom_circle(aes(x0 = x, y0 = y, r = r, fill = fill)) +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "none")

```

