# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pack_circles <- function(polygon, radii, existing_circles, max_attempts = 2000L, seed = 1L, neat_edges = TRUE) {
    .Call(`_pack_pack_circles`, polygon, radii, existing_circles, max_attempts, seed, neat_edges)
}

pack_polygons <- function(polygon, radii, sides, max_attempts = 2000L, seed = 1L, neat_edges = TRUE) {
    .Call(`_pack_pack_polygons`, polygon, radii, sides, max_attempts, seed, neat_edges)
}

